config/routes.rb
Rails.application.routes.draw do
  root 'main#home'

  resources :spirits

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spirit.rb
class Spirit < ApplicationRecord

  belongs_to :user
  validates :name, presence: true, length: {minimum: 3}

end

app/models/user.rb
class User < ApplicationRecord

  has_many :spirits

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/spirits_controller.rb
class SpiritsController < ApplicationController
  before_action :set_spirit, only: [:show, :edit, :update, :destroy]

  def index
    @spirits = Spirit.all
  end

  def new
    @spirit = Spirit.new
  end

  def show
    
  end

  def edit
    
  end
  
  def create
    @spirit = Spirit.new(spirit_params)
    if @spirit.save
      flash[:notice] = "Spirit was created successfully"
      redirect_to spirits_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @spirit.update(spirit_params)
      flash[:notice] = "Spirit was updated successfully"
      redirect_to spirits_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @spirit.destroy
    redirect_to spirits_path
  end

  private

  def spirit_params
    (params.require(:spirit).permit(:name, :abv, :spirit_type, :user_id))
  end

  def set_spirit
    @spirit = Spirit.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spirits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>

app/views/spirits/edit.html.erb
<%= form_with model: @spirit, local: true do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name of Spirit" %>
  </div>
  <div>
    <%= f.label :abv %>
    <%= f.text_field :abv, placeholder: "ABV of spirit" %>
  </div>
  <div>
    <%= f.label :spirit_type %>
    <%= f.text_field :spirit_type, placeholder: "Type of spirit" %>
  </div>
  <%= f.submit "Update Spirit"%>
  
<% end %>

app/views/spirits/index.html.erb
This is the spirits page

<br>

Spirit Name: 
<% @spirits.each do |spirit| %>
  Spirit Name: <%= link_to "#{spirit.name}", spirit_path(spirit) %>
  Spirit ABV: <%= spirit.abv %>
  Spirit Type: <%= spirit.spirit_type %>
  <br>
<% end %>

<br>
<%= link_to "Create a new spirit", new_spirit_path%>

app/views/spirits/new.html.erb
<h3>This is your spirit creation page.</h3>
<%= form_with model: @spirit do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :spirit_type %>
    <%= form.text_field :spirit_type %>
  </div>
  <div>
    <%= form.label :abv %>
    <%= form.number_field :abv %>
  </div>
  <div>
    <%= form.select :user_id, User.all.map {|u| [u.name, u.id]} %>
  </div>
  <%= form.submit %>
  
<% end %>

<br>
<%= link_to "Back to Spirits Index", spirits_path%>

app/views/spirits/show.html.erb
<h3>This is your <%= "#{@spirit.name}" %> show page. </h3>
<%= @spirit.name %>


<br>

<%= link_to "Delete", spirit_path(@spirit), class: "btn", data: { "turbo-method": :delete, confirm: "Are you sure?" } %>
<%= link_to "Edit your spirit", edit_spirit_path, class: "btn"%>